export default {
  GET:         'TASK_GET',
  GET_SUCCESS: 'TASK_GET_SUCCESS',
  GET_FAILURE: 'TASK_GET_FAILURE',

  GET_ID:         'TASK_GET_ID',
  GET_ID_SUCCESS: 'TASK_GET_ID_SUCCESS',
  GET_ID_FAILURE: 'TASK_GET_ID_FAILURE',

  POST:         'TASK_POST',
  POST_SUCCESS: 'TASK_POST_SUCCESS',
  POST_FAILURE: 'TASK_POST_FAILURE',

  UPDATE:         'TASK_UPDATE',
  UPDATE_SUCCESS: 'TASK_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TASK_UPDATE_FAILURE',
}